# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a34119ea56269e035c7413066e56bd9a3c80da12527d8d643b545bf693c8eb1848623ed4ccab3dc907adb123bd0e9f5106135a59e7421d1528c74a656c176c8

test:
  secret_key_base: 0b31e6856c8c7cd07adc98af137d4e4f46d3f31b17314517c16971a42f1be2781c6b4d2fc67ef04c955edfa82b61ea906dd729cbbe54d458213d75648109d823

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
